begin;
insert into auth.users(id) select md5('fa-weekly-'||n)::uuid from generate_series(1,4) n;
insert into public.photo_uploads(user_id,path) select md5('fa-weekly-'||n)::uuid,'test/weekly-'||n||'.jpg' from generate_series(1,3) n;
insert into public.submissions(id,author_id,title,description,category,image_path,status) select md5('fa-weekly-find-'||n)::uuid,md5('fa-weekly-'||n)::uuid,'Weekly test '||n,'','Other','test/weekly-'||n||'.jpg','approved' from generate_series(1,3) n;
insert into public.votes(user_id,submission_id,value) values(md5('fa-weekly-1')::uuid,md5('fa-weekly-find-1')::uuid,1),(md5('fa-weekly-4')::uuid,md5('fa-weekly-find-1')::uuid,1);
do $$begin if (select points from public.weekly_discoverers() where member_id=md5('fa-weekly-1')::uuid) is distinct from 6 then raise exception 'FAIL nonself vote score';end if;if (select points from public.weekly_discoverers() where member_id=md5('fa-weekly-2')::uuid) is distinct from 5 then raise exception 'FAIL find points';end if;end$$;
update public.submissions set status='hidden' where id=md5('fa-weekly-find-3')::uuid;
do $$begin if exists(select 1 from public.weekly_discoverers() where member_id=md5('fa-weekly-3')::uuid) then raise exception 'FAIL hidden discovery in rankings';end if;end$$;
insert into public.photo_uploads(user_id,path) select md5('fa-weekly-4')::uuid,'test/quota-'||n||'.jpg' from generate_series(1,10) n;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('fa-weekly-4')::text,true);
do $$begin begin perform public.reserve_photo_upload();raise exception 'FAIL member quota';exception when raise_exception then if sqlerrm not like 'Daily submission upload limit%' then raise;end if;end;end$$;
reset role;
update public.profiles set is_moderator=true where id=md5('fa-weekly-4')::uuid;
set local role authenticated;
select set_config('request.jwt.claim.sub',md5('fa-weekly-4')::text,true);
select public.reserve_photo_upload();
reset role;
select 'PASS: leaderboard excludes self votes and hidden content; member quota preserved; moderator curation permitted' as result;
rollback;
