import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
function worker(fail=false){const handlers={},saved=[];const self={location:{origin:'https://fuckinawesome.com'},addEventListener:(name,fn)=>handlers[name]=fn};const indexedDB={open(){const r={};queueMicrotask(()=>{if(fail){r.onerror();return}r.result={transaction(){const t={objectStore:()=>({put:(draft,key)=>{saved.push({draft,key});queueMicrotask(()=>t.oncomplete())}})};return t},close(){}};r.onsuccess()});return r}};vm.runInNewContext(fs.readFileSync(new URL('../public/share-worker.js',import.meta.url),'utf8'),{self,indexedDB,URL,Response,Date});return {handlers,saved};}
async function share(w,form,url='https://fuckinawesome.com/share-target',method='POST'){let result;w.handlers.fetch({request:{url,method,formData:async()=>form},respondWith:p=>result=p});return result?await result:null;}
test('share target stores a local photo and text before redirect, with bounded strings',async()=>{const w=worker(),f=new FormData();f.set('title','a'.repeat(200));f.set('text','https://example.com');f.set('photos',new Blob(['photo'],{type:'image/jpeg'}),'cover.jpg');const r=await share(w,f);assert.equal(r.status,303);assert.equal(r.headers.get('location'),'https://fuckinawesome.com/?share=1');assert.equal(w.saved.length,1);assert.equal(w.saved[0].key,'latest');assert.equal(w.saved[0].draft.title.length,140);assert.equal(w.saved[0].draft.photo.size,5);});
test('unrelated requests are never intercepted',async()=>{const w=worker();assert.equal(await share(w,new FormData(),'https://other.com/share-target'),null);assert.equal(await share(w,new FormData(),'https://fuckinawesome.com/'),null);assert.equal(await share(w,new FormData(),undefined,'GET'),null);});
test('unsupported photos and failed storage return actionable errors without saving',async()=>{const w=worker(),f=new FormData();f.set('photos',new Blob(['x'],{type:'text/html'}),'bad.html');assert.match((await share(w,f)).headers.get('location'),/share_error=photo/);assert.equal(w.saved.length,0);assert.match((await share(worker(true),new FormData())).headers.get('location'),/share_error=draft/);});
