'use client';
import {useState,useRef} from 'react';
import {requestScreening} from '../lib/request-screening';
import {db} from '../lib/supabase';
import {preparePhoto} from '../lib/photo';
import {safeLink} from '../lib/ranking.mjs';
export default function CuratedImport({onPublished}){
 const [items,setItems]=useState([]),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const files=useRef(new Map());
 async function choose(e){setMessage('');setResults([]);setItems([]);files.current=new Map([...e.target.files].map(f=>[f.name,f]));try{const manifest=[...files.current.values()].find(f=>f.name.endsWith('.json'));if(!manifest)throw Error('Include the collection manifest and its JPG covers.');const list=JSON.parse(await manifest.text());if(!Array.isArray(list)||!list.length||list.length>150)throw Error('Choose a collection of 1–150 discoveries.');for(const x of list){if(!safeLink(x.url)||!x.title||!x.description||!files.current.has(x.imageFile))throw Error('Every discovery needs its source, description, and matching cover.')}setItems(list);setMessage(list.length+' sourced discoveries ready to publish.')}catch(e){setMessage(e.message)}}
 async function publish(){setBusy(true);setResults([]);let published=0;try{for(const x of items){setMessage('Publishing '+(published+1)+' / '+items.length+': '+x.title);try{const existing=await db.from('submissions').select('id,status').eq('url',x.url).in('status',['pending','approved']).maybeSingle();if(existing.error)throw existing.error;if(existing.data){setResults(r=>[...r,{title:x.title,status:'Already exists',id:existing.data.id}]);continue}const photo=await preparePhoto(files.current.get(x.imageFile));const reservation=await db.rpc('reserve_photo_upload');if(reservation.error)throw reservation.error;const upload=await db.storage.from('discovery-photos').upload(reservation.data,photo,{contentType:'image/jpeg',cacheControl:'60'});if(upload.error)throw upload.error;const result=await db.rpc('submit_tagged_photo',{discovery_title:x.title,discovery_description:x.description,discovery_category:x.category,photo_path:reservation.data,discovery_url:x.url,discovery_tags:x.tags||[]});if(result.error)throw result.error;const verdict=await requestScreening('discovery',result.data);if(verdict!=='passed')throw Error('Submitted privately. Safety screening must pass before publication.');const approved=await db.rpc('moderate_discovery',{discovery_id:result.data,new_status:'approved'});if(approved.error)throw approved.error;published++;setResults(r=>[...r,{title:x.title,status:'Published',id:result.data}]);}catch(e){setResults(r=>[...r,{title:x.title,status:e.message||'Failed'}]);}}setMessage(published+' new discoveries published.');onPublished?.()}finally{setBusy(false)}}
 return <section className="category-requests"><h3>Curated collection</h3><p>Publish a sourced collection with prepared covers and tags. Duplicates are skipped. No votes are added.</p><label>Collection manifest and cover photos<input type="file" multiple accept="application/json,image/jpeg" disabled={busy} onChange={choose}/></label><button disabled={busy||!items.length} onClick={publish}>Publish curated collection</button><p role="status">{message}</p><details open={results.length>0}><summary>Publication results ({results.length})</summary>{results.map((x,i)=><p key={i}>{x.status}: {x.title}{x.id&&<> · <a href={'/?discovery='+x.id}>View</a></>}</p>)}</details></section>
}
