'use client';
import {useState} from 'react';
import {trackUsage} from '../lib/usage';
export default function DiscoveryShare({item,onShare}){
 const [open,setOpen]=useState(false),[format,setFormat]=useState('portrait'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[imageError,setImageError]=useState(false);
 const url=`/discovery/${item.id}/share?format=${format}`;
 async function download(){if(busy)return;setBusy(true);setMessage('');try{const response=await fetch(url);if(!response.ok)throw Error();const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);const link=document.createElement('a');link.href=objectUrl;link.download=`fuckinawesome-${format}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);trackUsage('share');setMessage('Image downloaded. Include the discovery link in your caption.')}catch{setMessage('The share image could not load. Try again or share the discovery link.')}finally{setBusy(false)}}
 async function shareImage(){if(busy)return;setBusy(true);setMessage('');try{const response=await fetch(url);if(!response.ok)throw Error();const file=new File([await response.blob()],'fuckinawesome.png',{type:'image/png'});if(!navigator.canShare?.({files:[file]})){setMessage('Download the image, then upload it to your social app.');return}await navigator.share({files:[file],title:item.title,text:item.title+' — Fuckin Awesome, Meh or Bullshit? Vote: '+location.origin+'/discovery/'+item.id});trackUsage('share')}catch(error){if(error.name!=='AbortError')setMessage('Could not share this image. Download it instead.')}finally{setBusy(false)}}
 if(item.status!=='approved')return <p className="muted">Share images become available after your discovery is approved.</p>;
 return <div className="discovery-share" data-no-swipe><div className="actions"><button type="button" onClick={()=>onShare(item)}>Share link</button><button type="button" aria-expanded={open} onClick={()=>setOpen(x=>!x)}>Create social image</button></div>{open&&<section className="share-image-panel"><h3>Put it to a vote.</h3><label>Image size<select value={format} onChange={e=>{setFormat(e.target.value);setImageError(false)}}><option value="portrait">Feed post · 1080 × 1350</option><option value="square">Square · 1080 × 1080</option><option value="story">Story · 1080 × 1920</option></select></label>{imageError?<p>Preview unavailable. Share the link or try downloading again.</p>:<img key={url} className="share-image-preview" src={url} alt={'Social image preview for '+item.title} onError={()=>setImageError(true)}/>}<div className="actions"><button type="button" className="primary" disabled={busy} onClick={download}>{busy?'Preparing image…':'Download PNG'}</button>{typeof navigator!=='undefined'&&navigator.share&&<button type="button" disabled={busy} onClick={shareImage}>Share image</button>}</div><p className="muted">Share images you have permission to use. Keep source credits and include the discovery link so people can vote.</p>{message&&<p role="status">{message}</p>}</section>}</div>
}
