'use client';
import {useEffect,useState} from 'react';
import {db} from '../lib/supabase';
export function FollowButton({kind,target,following,onFollow,busy,label}){return <button type="button" className={'follow-button '+(following?'is-following':'')} aria-pressed={following} disabled={busy} onClick={()=>onFollow(kind,target,!following)}>{following?'✓ Following':'+ Follow'}{label?' '+label:''}</button>}
export default function Following({follows,categories,topics,onFollow,busy,onBrowse,onDone}){
 const [names,setNames]=useState({});
 useEffect(()=>{let active=true;const ids=follows.filter(x=>x.kind==='discoverer').map(x=>x.target);if(ids.length)db.from('profiles').select('id,display_name').in('id',ids).then(({data})=>{if(active)setNames(Object.fromEntries((data||[]).map(x=>[x.id,x.display_name])))});return()=>{active=false}},[follows]);
 const has=(kind,target)=>follows.some(x=>x.kind===kind&&x.target===target);
 return <section className="following-settings"><p>Follow the things you’re into. Your For You feed combines their discoveries with finds from people you follow.</p><h3>Categories</h3><div className="follow-options">{categories.map(category=><FollowButton key={category} kind="category" target={category} label={category} following={has('category',category)} onFollow={onFollow} busy={busy}/>)}</div><h3>Discovered interests</h3><div className="follow-options">{topics.filter(topic=>!categories.some(category=>category.toLowerCase()===topic.tag)).map(topic=><FollowButton key={topic.tag} kind="tag" target={topic.tag} label={topic.tag} following={has('tag',topic.tag)} onFollow={onFollow} busy={busy}/>)}</div><h3>Your following</h3>{!follows.length?<p className="muted">Pick a few interests above to make this yours.</p>:<ul className="following-list">{follows.map(follow=><li key={follow.kind+follow.target}><button type="button" className="following-name" onClick={()=>onBrowse(follow.kind,follow.target)}>{follow.kind==='discoverer'?(names[follow.target]||'Discoverer'):follow.target}<small>{follow.kind==='discoverer'?'Discoverer':follow.kind==='category'?'Category':'Interest'}</small></button><button type="button" disabled={busy} aria-label={'Unfollow '+(names[follow.target]||follow.target)} onClick={()=>onFollow(follow.kind,follow.target,false)}>Unfollow</button></li>)}</ul>}<p className="muted">Your following list is private. Follow a discoverer from their profile or an opened discovery.</p><button type="button" className="primary" disabled={busy} onClick={onDone}>Explore For You</button></section>
}
