'use client';
import {useEffect, useState, useRef} from 'react';
import {db, configured} from '../lib/supabase';
import {score, safeLink} from '../lib/ranking.mjs';
const categories = ['Architecture','Technology','Adventure','Food','Machines','Art','Other'];
const emoji = {Architecture:'🏠',Technology:'🚀',Adventure:'🏔️',Food:'🍔',Machines:'🚗',Art:'🎨',Other:'🔥'};
export default function Hall() {
  const dialogRef=useRef(null);
  const [member,setMember]=useState(null);
  const [user,setUser]=useState(null),[items,setItems]=useState([]),[votes,setVotes]=useState({}),[profile,setProfile]=useState(null),[view,setView]=useState('Trending'),[category,setCategory]=useState('All'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(configured),[modal,setModal]=useState(null),[detail,setDetail]=useState(null),[publicProfile,setPublicProfile]=useState(null),[reports,setReports]=useState([]);
  const [page,setPage]=useState(0),[hasMore,setHasMore]=useState(false);
  const loadVersion=useRef(0);
  async function load() {
    if(!db)return;
    const version=++loadVersion.current;
    setLoading(true);
    const {data,error}=await db.rpc('discovery_feed',{feed:view,selected_category:category,member_id:publicProfile,discovery_id:detail,page_offset:page*50});
    if(version!==loadVersion.current)return;
    setHasMore(!error&&(data?.length||0)>50);
    if(error)setMessage('Could not load discoveries. Please try again.'); else setItems((data||[]).slice(0,50));
    setLoading(false);
  }
  useEffect(()=>{ if(!db)return; let active=true; db.auth.getUser().then(({data})=>{if(active)setUser(data.user)}); const {data}=db.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null)); const params=new URLSearchParams(location.search); setDetail(params.get('discovery')); setPublicProfile(params.get('profile')); return ()=>{active=false;data.subscription.unsubscribe()}; },[]);
  useEffect(()=>{ if(!db||!user){setProfile(null);setVotes({});return;} db.from('profiles').select('*').eq('id',user.id).single().then(({data})=>setProfile(data)); db.from('votes').select('submission_id,value').eq('user_id',user.id).then(({data})=>setVotes(Object.fromEntries((data||[]).map(x=>[x.submission_id,x.value])))); },[user]);
  useEffect(()=>{let active=true;setMember(null);if(db&&publicProfile)db.from('profiles').select('display_name,bio').eq('id',publicProfile).maybeSingle().then(({data})=>{if(active)setMember(data)});return()=>{active=false};},[publicProfile]);
  useEffect(()=>{load();return()=>{loadVersion.current++};},[user,view,category,publicProfile,detail,page]);
  useEffect(()=>{if(!modal)return;const previous=document.activeElement;const dialog=dialogRef.current;dialog?.querySelector('input,textarea,button')?.focus();function keys(e){if(e.key==='Escape'){setModal(null);return}if(e.key==='Tab'){const controls=[...dialog.querySelectorAll('button,input,textarea,select,a[href]')].filter(x=>!x.disabled);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);previous?.focus()};},[modal]);
  async function act(task) {if(busy)return;setBusy(true);setMessage('');try{await task()}catch(error){setMessage(error.message||'Something went wrong. Try again.')}finally{setBusy(false)}}
  function requireUser(){if(!configured){setMessage('The community is getting ready. Accounts and voting open when setup is complete.');return false;}if(!user){setModal('login');return false;}return true;}
  async function vote(id,value){if(!requireUser())return;await act(async()=>{const {error}=await db.rpc('cast_vote',{discovery_id:id,vote_value:votes[id]===value?0:value});if(error)throw error;setVotes(v=>({...v,[id]:v[id]===value?0:value}));await load()})}
  async function submit(event){event.preventDefault();const f=new FormData(event.currentTarget);await act(async()=>{const url=safeLink(f.get('url'));if(!url)throw Error('Use a complete http or https link.');const {error}=await db.rpc('submit_discovery',{discovery_title:f.get('title').trim(),discovery_description:f.get('description').trim(),discovery_url:url,discovery_category:f.get('category')});if(error)throw error;setModal(null);setMessage('Submitted! A moderator will check your discovery before it goes live.');await load()})}
  async function login(event){event.preventDefault();const email=new FormData(event.currentTarget).get('email');await act(async()=>{const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});if(error)throw error;setMessage('Check your email for your sign-in link.');setModal(null)})}
  async function share(item){const url=new URL(location.origin);url.searchParams.set('discovery',item.id);try{if(navigator.share)await navigator.share({title:item.title,url:url.href});else{await navigator.clipboard.writeText(url.href);setMessage('Link copied. Spread the awesome.')}}catch(e){if(e.name!=='AbortError')setMessage('Copy this link: '+url.href)}}
  async function moderate(id,status){await act(async()=>{const {error}=await db.rpc('moderate_discovery',{discovery_id:id,new_status:status});if(error)throw error;await load()})}
  async function openModeration(){setView('Moderation');const {data,error}=await db.from('reports').select('*').is('resolved_at',null).order('created_at',{ascending:false}).limit(100);if(error)setMessage('Could not load reports.');else setReports(data||[])}
  async function resolveReport(id){await act(async()=>{const {error}=await db.rpc('resolve_report',{report_id:id});if(error)throw error;setReports(rows=>rows.filter(r=>r.id!==id));setMessage('Report marked handled.')})}
  async function saveProfile(event){event.preventDefault();const f=new FormData(event.currentTarget);await act(async()=>{const {error}=await db.from('profiles').update({display_name:f.get('display_name').trim(),bio:f.get('bio').trim()}).eq('id',user.id);if(error)throw error;setProfile(p=>({...p,display_name:f.get('display_name').trim(),bio:f.get('bio').trim()}));setMessage('Profile saved.');setModal(null)})}
  async function report(event){event.preventDefault();const f=new FormData(event.currentTarget);await act(async()=>{const {error}=await db.rpc('report_discovery',{discovery_id:modal.id,report_reason:f.get('reason').trim()});if(error)throw error;setModal(null);setMessage('Report sent to the moderators. Thank you.')})}
  let visible=items.filter(x=>view==='Moderation'?true:x.status==='approved');
  if(view==='My discoveries')visible=items.filter(x=>x.author_id===user?.id);
  if(publicProfile)visible=visible.filter(x=>x.author_id===publicProfile);
  if(detail)visible=visible.filter(x=>x.id===detail);
  if(category!=='All')visible=visible.filter(x=>x.category===category);
  function reset(){setPage(0);setDetail(null);setPublicProfile(null);history.replaceState(null,'',location.pathname)}
  return <><header><div className="wrap nav"><a className="logo" href="/">FUCKIN<span>AWESOME</span></a><div className="actions"><button onClick={()=>{if(requireUser())setModal('submit')}}>Submit something</button>{user?<><button onClick={()=>setModal('profile')}>{profile?.display_name||'My profile'}</button><button disabled={busy} onClick={()=>act(async()=>{const {error}=await db.auth.signOut();if(error)throw error;setView('Trending')})}>Sign out</button></>:<button onClick={()=>{if(configured)setModal('login');else requireUser()}}>Sign in</button>}</div></div></header>
  <main><section className="hero wrap"><div className="eyebrow">The internet’s hall of awesome</div><h1>Find something<br/>FUCKIN AWESOME.</h1><p>Discover incredible things, vote on the coolest shit on the internet, and show everyone what you found.</p><div className="actions"><button className="primary" onClick={()=>{const approved=items.filter(x=>x.status==='approved');if(approved.length){const x=approved[Math.floor(Math.random()*approved.length)];setPage(0);setDetail(x.id);setCategory('All');setPublicProfile(null)}else setMessage('The hall is waiting for its first discovery. Submit something awesome.')}}>🔥 Show me something fuckin awesome</button><button className="secondary" onClick={()=>{if(requireUser())setModal('submit')}}>Submit something</button></div></section>
  <section className="wrap"><div role="status" aria-live="polite" className={message?'notice':''}>{message}</div>{!configured&&<p className="notice">The hall is getting ready for real discoveries. Community features are not open yet.</p>}<div className="tabs">{['Trending','New','Hall of Fame',...(user?['My discoveries']:[])].map(x=><button key={x} aria-pressed={view===x} onClick={()=>{reset();setView(x)}}>{x}</button>)}{profile?.is_moderator&&<button onClick={()=>{reset();openModeration()}}>Moderation</button>}</div><div className="sectionhead"><div><h2>{detail?'One fuckin awesome discovery':publicProfile?(member?.display_name||'Discoveries from this member'):view==='Trending'?'🔥 Trending now':view}</h2><p className="muted">{publicProfile?(member?.bio||'Discoveries shared with the hall.'):view==='Trending'?'Real votes. Fresh discoveries. You decide what’s awesome.':view==='Hall of Fame'?'The community’s highest net scores.':'Find your next obsession.'}</p></div><label>Category <select value={category} onChange={e=>{setPage(0);setCategory(e.target.value)}}>{['All',...categories].map(x=><option key={x}>{x}</option>)}</select></label></div>{(detail||publicProfile)&&<button onClick={reset}>← Back to discoveries</button>}
  {loading?<p>Loading discoveries…</p>:<div className="grid">{visible.map(x=><article className="card" key={x.id}><div className="pic" aria-hidden="true">{emoji[x.category]||'🔥'}</div><div className="content"><div className="tag">{x.category} {x.status!=='approved'&&`· ${x.status}`}</div><h3><a href={safeLink(x.url)||'#'} target="_blank" rel="noopener noreferrer">{x.title} ↗</a></h3><p>{x.description}</p><a className="muted" href={`/?profile=${x.author_id}`}>By {x.author_name||'a discoverer'}</a><div className="score">{score(x.up_votes,x.down_votes)===null?'No votes yet':`${score(x.up_votes,x.down_votes)}% awesome`} <span className="muted">· {x.up_votes+x.down_votes} votes</span></div>{x.status==='approved'&&<div className="voting"><button disabled={busy} aria-pressed={votes[x.id]===1} onClick={()=>vote(x.id,1)}>🔥 FUCKIN AWESOME</button><button disabled={busy} aria-pressed={votes[x.id]===-1} onClick={()=>vote(x.id,-1)}>NOT FUCKIN AWESOME</button></div>}<div className="cardactions"><button onClick={()=>share(x)}>Share</button>{x.status==='approved'&&<button onClick={()=>{if(requireUser())setModal({type:'report',id:x.id})}}>Report</button>}{view==='Moderation'&&<><button disabled={busy} onClick={()=>moderate(x.id,'approved')}>Approve</button><button disabled={busy} onClick={()=>moderate(x.id,'rejected')}>Reject</button><button disabled={busy} onClick={()=>moderate(x.id,'hidden')}>Hide</button></>}</div></div></article>)}</div>}{!loading&&!visible.length&&<div className="empty"><h3>{detail?'This discovery isn’t available.':'The next awesome discovery could be yours.'}</h3><p>No discoveries to show here yet.</p><button className="primary" onClick={()=>{if(requireUser())setModal('submit')}}>Submit a discovery</button></div>}
  {!loading&&!detail&&<nav className="actions" aria-label="Discovery pages"><button disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={!hasMore||busy} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}
  {view==='Moderation'&&<section><h2>Community reports</h2>{reports.length===0?<p>No reports.</p>:reports.map(r=><div className="notice" key={r.id}><a href={`/?discovery=${r.submission_id}`}>View reported discovery</a><p>{r.reason}</p><button disabled={busy} onClick={()=>moderate(r.submission_id,'hidden')}>Hide discovery</button><button disabled={busy} onClick={()=>resolveReport(r.id)}>Mark handled</button></div>)}</section>}</section></main>
  <footer>© 2026 Fuckin Awesome. Built for people who know awesome when they see it.</footer>
  {modal&&<div className="backdrop"><section ref={dialogRef} className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button className="close" aria-label="Close dialog" onClick={()=>setModal(null)}>×</button><h2 id="dialog-title">{modal==='login'?'Join the hall.':modal==='submit'?'Show us something fuckin awesome.':modal==='profile'?'Your corner of awesome.':'Something wrong with this discovery?'}</h2>{modal==='login'?<form onSubmit={login}><p>We’ll email you a sign-in link. No password to remember.</p><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><button className="primary" disabled={busy}>Send sign-in link</button></form>:modal==='submit'?<form onSubmit={submit}><label>Title<input name="title" required minLength={5} maxLength={140}/></label><label>Link<input name="url" type="url" required maxLength={2048}/></label><label>Why is it awesome?<textarea name="description" required minLength={10} maxLength={1000}/></label><label>Category<select name="category">{categories.map(x=><option key={x}>{x}</option>)}</select></label><p className="muted">Share the original source. No spam, hate, illegal content, or private personal information. Submissions are reviewed before publication.</p><button className="primary" disabled={busy}>Submit for review</button></form>:modal==='profile'?<form onSubmit={saveProfile}><label>Display name<input name="display_name" required minLength={2} maxLength={40} defaultValue={profile?.display_name}/></label><label>Bio<textarea name="bio" maxLength={280} defaultValue={profile?.bio}/></label><button className="primary" disabled={busy}>Save profile</button></form>:<form onSubmit={report}><label>What should the moderators know?<textarea name="reason" required minLength={10} maxLength={500}/></label><button className="primary" disabled={busy}>Send report</button></form>}<div role="alert">{message}</div></section></div>}</>;
}



