'use client';
import {useEffect,useRef,useState} from 'react';
import {LevelBadge} from './voter-progress';
import {db} from '../lib/supabase';
export default function ProfileMenu({user,profile,photo,levelStats,busy,revision,onLogin,onProfile,onDiscoveries,onSaved,onModeration,onNotifications,onFollowing,onSignOut}){
 const [open,setOpen]=useState(false),[unread,setUnread]=useState(false);
 const root=useRef(null),trigger=useRef(null);
 useEffect(()=>{if(!user||!db){setUnread(false);setOpen(false);return;}let active=true,inFlight=false;
 async function refresh(){if(inFlight||document.visibilityState==='hidden')return;inFlight=true;try{const {count,error}=await db.from('discovery_notifications').select('id',{count:'exact',head:true}).eq('user_id',user.id).is('read_at',null);if(active&&!error)setUnread(count>0);}finally{inFlight=false;}}
 refresh();const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)};
 },[user?.id,revision]);
 useEffect(()=>{if(!open)return;function outside(e){if(!root.current?.contains(e.target))setOpen(false)}function escape(e){if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open]);
 function choose(action){setOpen(false);trigger.current?.focus();action();}
 return <div className="profile-control" ref={root}><button ref={trigger} className="profile-trigger" aria-label={user?(unread?'Profile, unread notifications':'Profile'):'Sign in'} aria-expanded={user?open:undefined} aria-controls={user?'profile-options':undefined} onClick={()=>user?setOpen(x=>!x):onLogin()}>{photo?<img className="member-avatar" src={photo} alt=""/>:<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></svg>}{user&&unread&&<span className="notification-dot" aria-hidden="true"/>}</button>{user&&open&&<div id="profile-options" className="profile-options"><span className="profile-name">{profile?.display_name||'Your account'} <LevelBadge stats={levelStats}/></span><button onClick={()=>choose(onProfile)}>My profile</button><button onClick={()=>choose(onFollowing)}>Following & interests</button><button onClick={()=>choose(onDiscoveries)}>My discoveries</button><button onClick={()=>choose(onSaved)}>Saved discoveries</button><button onClick={()=>choose(onNotifications)}>Notifications {unread&&<span className="menu-unread">Unread</span>}</button>{profile?.is_moderator&&<button onClick={()=>choose(onModeration)}>Moderation</button>}<hr/><button disabled={busy} onClick={()=>choose(onSignOut)}>Sign out</button></div>}</div>;
}
