'use client';
import {useEffect,useState} from 'react';
import {requestScreening} from '../lib/request-screening';
import ContentScreen from './content-screen';
import {db} from '../lib/supabase';
export default function ProfilePhoto({user,moderator=false,reviewOnly=false,onChanged=()=>{}}){
 const [own,setOwn]=useState(null),[pending,setPending]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await db.from('profile_photos').select('*').eq('user_id',user.id).maybeSingle();if(!r.error)setOwn(r.data);if(moderator){const q=await db.from('profile_photos').select('*').not('pending_image','is',null).order('updated_at').limit(100);if(!q.error)setPending(q.data||[])}}
 useEffect(()=>{load()},[user.id,moderator]);
 const provider=user.user_metadata?.avatar_url;let providerPhoto=null;try{const u=new URL(provider);if(u.protocol==='https:'&&(/(^|\.)googleusercontent\.com$/.test(u.hostname)||/(^|\.)facebook\.com$/.test(u.hostname)||/(^|\.)fbcdn\.net$/.test(u.hostname)))providerPhoto=u.href}catch{}
 async function choose(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);setMessage('');try{if(file.size>20*1024*1024)throw Error('Choose a photo under 20 MB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const side=Math.min(bitmap.width,bitmap.height);canvas.getContext('2d').drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();const data=canvas.toDataURL('image/jpeg',.82);if(data.length>=200000)throw Error('Choose a simpler photo.');const r=await db.rpc('submit_profile_photo',{image_data:data});if(r.error)throw r.error;const verdict=await requestScreening('profile',user.id);setMessage(verdict==='passed'?'Safety screening passed. Your photo is awaiting moderator approval.':verdict==='blocked'||verdict==='review'?'Your photo was flagged by safety screening and cannot be published. Choose an appropriate replacement.':'Your photo is private and awaiting safety screening and moderator approval.');await load();onChanged()}catch(err){setMessage(err.message||'Photo upload failed. Try JPG or PNG.')}finally{setBusy(false)}}
 async function review(id,approve){if(approve&&!window.confirm('I reviewed this profile photo. It contains no nudity or prohibited content. Approve?'))return;setBusy(true);try{const r=await db.rpc('review_profile_photo',{member_id:id,approve});if(r.error)throw r.error;await load();onChanged()}catch(err){setMessage(err.message)}finally{setBusy(false)}}
 return <section className="profile-photo-editor"><h3>{reviewOnly?'Profile photos awaiting review':'Profile picture'}</h3>{!reviewOnly&&<>{(own?.approved_image||providerPhoto)&&<img className="member-avatar large" src={own?.approved_image||providerPhoto} alt="Your profile picture" referrerPolicy="no-referrer"/>}<label>Upload a profile photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={choose}/></label><p className="muted">Your photo is cropped to a square and location metadata is removed. Use an appropriate photo you have permission to share. Uploads require approval.</p>{own?.pending_image&&<><img className="member-avatar large" src={own.pending_image} alt="Pending profile photo"/><p>Awaiting moderation</p></>}{own?.status==='rejected'&&<p>Your last photo was rejected. Choose another.</p>}</>}{message&&<p role="status">{message}</p>}{moderator&&pending.length>0&&<><h3>Profile photos awaiting review</h3>{pending.map(p=><div key={p.user_id}><img className="member-avatar large" src={p.pending_image} alt="Profile photo awaiting review"/><ContentScreen id={p.user_id} kind="profile"/><a href={`/?profile=${p.user_id}`}>View member</a><div className="actions"><button type="button" disabled={busy} onClick={()=>review(p.user_id,true)}>Approve photo</button><button type="button" disabled={busy} onClick={()=>review(p.user_id,false)}>Reject photo</button></div></div>)}</>}</section>
}
