'use client';
import {useEffect,useState} from 'react';
import {db} from '../lib/supabase';
import {hallProgress} from '../lib/hall-moments.mjs';
import DiscoveryPhoto from './discovery-photo';
export default function RaceToHall({category,tag,query,kind='awesome',revision,onOpen}){
 const [state,setState]=useState({items:[],loading:true,error:false});
 useEffect(()=>{if(!db)return;let active=true;setState({items:[],loading:true,error:false});db.rpc('hall_contenders',{selected_category:category,selected_tag:tag,search_query:query||null,hall_kind:kind}).then(({data,error})=>{if(active)setState({items:data||[],loading:false,error:!!error})});return()=>{active=false}},[category,tag,query,kind,revision]);
 return <section className="race-to-hall" aria-label="Race to the Hall"><div className="race-heading"><span className="eyebrow">YOU PICK THE WINNERS</span><h3>{kind==='bullshit'?'Race to the Hall of Bullshit':'Race to the Hall'}</h3><p>Every winner starts here. 10+ real votes and more than 80% {kind==='bullshit'?'Bullshit':'Awesome'} to qualify.</p></div>{state.loading?<p>Finding contenders…</p>:state.error?<p role="status">Contenders couldn’t load. You can still browse and vote below.</p>:!state.items.length?<p>No contenders in this selection yet. Share the first one.</p>:<div className="race-contenders">{state.items.map(item=>{const p=hallProgress(item,kind);return <article className="race-contender" key={item.id}><DiscoveryPhoto path={item.image_path} title={item.title} discoveryId={item.id} sourceUrl={item.url} onOpen={()=>onOpen(item)}/><div><button className="race-title" onClick={()=>onOpen(item)}>{item.title}</button><span>{p.total} votes · {p.percent.toFixed(1).replace(/\.0$/,'')}% {kind==='bullshit'?'bullshit':'awesome'}</span><progress max={10} value={Math.max(0,10-Math.min(10,p.needed))} aria-label={`Qualification progress: ${p.needed} more ${kind} votes needed`}/><strong>{p.needed} more {kind==='bullshit'?'Bullshit':'Awesome'} {p.needed===1?'vote':'votes'} needed</strong><small>If other votes stay the same.</small></div></article>})}</div>}</section>;
}
