'use client';
import {useEffect,useRef} from 'react';
import DiscoveryPhoto from './discovery-photo';
import {hallProgress} from '../lib/hall-moments.mjs';
export default function VotingRound({round,onClose,onAgain,onOpen,onShare,onHall}){
 const dialog=useRef(null);useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;previous?.focus()}},[]);
 const picks=round.results.filter(x=>x.choice===1),closest=[...picks].filter(x=>!hallProgress(x).qualified).sort((a,b)=>hallProgress(a).needed-hallProgress(b).needed)[0];
 return <dialog ref={dialog} className="discovery-dialog round-recap" aria-labelledby="round-title" onClose={onClose}><div className="viewer-navigation"><button autoFocus className="close" aria-label="Close round recap" onClick={onClose}>×</button></div><div className="discovery-dialog-copy"><span className="eyebrow">YOUR VERDICTS ARE IN</span><h2 id="round-title">{round.results.length===round.rows.length?'You helped decide what deserves the Hall.':'Every vote makes a difference.'}</h2><p>{round.results.length} discoveries voted on · {picks.length} Awesome · {round.results.filter(x=>x.choice===2).length} Meh · {round.results.filter(x=>x.choice===-1).length} Bullshit.</p><h3>Your Awesome picks</h3>{!picks.length?<p>Nothing won you over this round. That’s a verdict too.</p>:<div className="round-picks">{picks.map(item=><article key={item.id}><DiscoveryPhoto path={item.image_path} title={item.title} discoveryId={item.id} sourceUrl={item.url} onOpen={()=>onOpen(item)}/><strong>{item.title}</strong><span>{hallProgress(item).qualified?'In the Hall of Fame':`${hallProgress(item).needed} more Awesome votes to qualify`}</span><div className="actions"><button onClick={()=>onOpen(item)}>Revisit</button><button onClick={()=>onShare(item)}>Invite a vote ↗</button></div></article>)}</div>}{closest&&<div className="round-contender"><h3>Closest contender you backed</h3><button onClick={()=>onOpen(closest)}>{closest.title}</button><p>{hallProgress(closest).needed} more Awesome votes needed, if other votes stay the same.</p></div>}<div className="actions"><button className="primary" onClick={onAgain}>Vote on another five</button><button onClick={onHall}>See the race to the Hall</button><button onClick={onClose}>Back to browsing</button></div><p className="muted">These picks reflect your votes. Save a discovery to keep it in your private collection.</p></div></dialog>;
}
