import sharp from 'sharp';
import {approvedWordmark} from './approved-wordmark.mjs';
export const socialFormats={portrait:{width:1080,height:1350,imageHeight:730},square:{width:1080,height:1080,imageHeight:520},story:{width:1080,height:1920,imageHeight:1200}};
export function xmlText(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]))}
export function titleLines(value,width=35,max=3){const words=String(value||'').replace(/\s+/g,' ').trim().split(' ');const lines=[''];for(const word of words){if((lines.at(-1)+' '+word).trim().length>width&&lines.at(-1)){if(lines.length===max){lines[max-1]=lines[max-1].slice(0,width-1)+'…';break}lines.push('')}lines[lines.length-1]=(lines.at(-1)+' '+word).trim()}return lines.map(line=>line.length>width?line.slice(0,width-1)+'…':line)}
export async function socialCard(photo,item,format='portrait'){
 const size=socialFormats[format];if(!size)throw Error('Unknown format');
 const image=await sharp(photo,{limitInputPixels:40000000}).rotate().resize(size.width,size.imageHeight,{fit:'cover'}).png().toBuffer();
 const up=Number(item.up_votes)||0,down=Number(item.down_votes)||0,neutral=Number(item.neutral_votes)||0,total=up+down+neutral;
 const y=140+size.imageHeight,lines=titleLines(item.title,35,format==='square'?2:3);
 const source=(()=>{try{return new URL(item.url).hostname.replace(/^www\./,'')}catch{return 'Community discovery'}})();
 const overlay=Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="${size.height}"><rect width="1080" height="140" fill="#111318"/><g transform="translate(62 35) scale(.68)">${approvedWordmark}</g><rect y="${y}" width="1080" height="${size.height-y}" fill="#111318"/><rect y="${y}" width="1080" height="7" fill="#ff8b32"/><text x="54" y="${y+61}" fill="#ff8b32" font-family="sans-serif" font-weight="bold" font-size="26">${xmlText(item.category?.toUpperCase())} · ${total.toLocaleString('en-US')} VOTES</text>${lines.map((line,i)=>`<text x="54" y="${y+120+i*53}" fill="#ffffff" font-family="sans-serif" font-weight="bold" font-size="46">${xmlText(line)}</text>`).join('')}<text x="54" y="${size.height-166}" fill="#ffffff" font-family="sans-serif" font-weight="bold" font-size="38">FUCKIN AWESOME OR BULLSHIT?</text><text x="54" y="${size.height-113}" fill="#cbd0d8" font-family="sans-serif" font-size="28">Awesome · Meh · Bullshit. You decide.</text><text x="54" y="${size.height-59}" fill="#ff8b32" font-family="sans-serif" font-weight="bold" font-size="31">Vote at fuckinawesome.com</text><text x="54" y="${size.height-22}" fill="#9ca5b1" font-family="sans-serif" font-size="17">${xmlText(source)} · Photo source and credits in the discovery</text></svg>`);
 return sharp({create:{width:size.width,height:size.height,channels:4,background:'#111318'}}).composite([{input:image,top:140,left:0},{input:overlay,top:0,left:0}]).png().toBuffer();
}
